// Export the template names as an enum for better maintainability when accessing them elsewhere
import esES from './es-es.json';
import esMX from './es-mx.json';

export enum StringTemplates {
  Contacts = 'PSContacts',
  MyContacts = 'PSMyContacts',
  SharedContacts = 'PSSharedContacts',
  Recent = 'PSContactsRecent',
  NoContacts = 'PSNoContacts',
  NoHistory = 'PSNoHistory',
  ClearHistory = 'PSClearHistory',
  ClearHistoryDialog = 'PSClearHistoryDialog',
  ContactChannel = 'PSContactChannel',
  ContactInboundCall = 'PSContactInboundCall',
  ContactOutboundCall = 'PSContactOutboundCall',
  ContactInboundAddress = 'PSContactInboundAddress',
  ContactCustomerAddress = 'PSContactCustomerAddress',
  ContactPhoneNumber = 'PSContactPhoneNumber',
  ClickToCall = 'PSClickToCall',
  ContactActions = 'PSContactActions',
  PlaceOutboundCall = 'PSPlaceOutboundCall',
  OutboundCallDialog = 'PSOutboundCallDialog',
  OutboundNumberToDial = 'PSOutboundNumberToDial',
  OutboundCallerId = 'PSOutboundCallerId',
  PlaceCall = 'PSPlaceCall',
  ContactName = 'PSContactName',
  ContactDefaultCustomer = 'PSContactDefaultCustomer',
  ContactDateTime = 'PSContactDateTime',
  ContactDuration = 'PSContactDuration',
  ContactQueue = 'PSContactQueue',
  ContactOutcome = 'PSContactOutcome',
  ContactNotes = 'PSContactNotes',
  ContactAdd = 'PSContactAdd',
  ContactDelete = 'PSContactDelete',
  ContactDeleteConfirm = 'PSContactDeleteConfirm',
  ContactEdit = 'PSContactEdit',
  OutboundContactHeader = 'PSOutboundContactHeader',
  OutboundContactLabel = 'PSOutboundContactLabel',
  ContactSearch = 'PSContactSearch',
  NoItems = 'PSContactNoItems',
  CurrentPage = 'PSContactCurrentPage',
  NextPage = 'PSContactNextPage',
  PreviousPage = 'PSContactPreviousPage',
  AllowColdTransfer = 'PSContactAllowColdTransfer',
  AllowWarmTransfer = 'PSContactAllowWarmTransfer',
}

export const stringHook = () => ({
  'en-US': {
    [StringTemplates.Contacts]: 'Contatos',
    [StringTemplates.MyContacts]: 'Meus Contatos',
    [StringTemplates.SharedContacts]: 'Contatos Compartilhados',
    [StringTemplates.Recent]: 'Recentes',
    [StringTemplates.NoContacts]: 'Nenhum contato foi criado ainda.',
    [StringTemplates.NoHistory]: 'As chamadas e chats aparecerão aqui quando forem concluídos.',
    [StringTemplates.ClearHistory]: 'Limpar Histórico',
    [StringTemplates.ClearHistoryDialog]: 'Confirme que deseja excluir todo o seu histórico de contatos.',
    [StringTemplates.ContactChannel]: 'Canal',
    [StringTemplates.ContactInboundCall]: 'Chamada Recebida',
    [StringTemplates.ContactOutboundCall]: 'Chamada Realizada',
    [StringTemplates.ContactInboundAddress]: 'Endereço de Entrada',
    [StringTemplates.ContactCustomerAddress]: 'Endereço do Cliente',
    [StringTemplates.ContactPhoneNumber]: 'Número de Telefone',
    [StringTemplates.ClickToCall]: 'Clique para fazer uma chamada',
    [StringTemplates.ContactActions]: 'Ações',
    [StringTemplates.PlaceOutboundCall]: 'Realizar Chamada de Saída',
    [StringTemplates.OutboundCallDialog]: 'Por favor, confirme que deseja ligar',
    [StringTemplates.OutboundNumberToDial]: 'Número para Discar',
    [StringTemplates.OutboundCallerId]: 'Identificador de Chamadas',
    [StringTemplates.PlaceCall]: 'Fazer Chamada',
    [StringTemplates.ContactName]: 'Nome',
    [StringTemplates.ContactDefaultCustomer]: 'Cliente',
    [StringTemplates.ContactDateTime]: 'Data & Hora',
    [StringTemplates.ContactDuration]: 'Duração da Tarefa',
    [StringTemplates.ContactQueue]: 'Fila',
    [StringTemplates.ContactOutcome]: 'Resultado',
    [StringTemplates.ContactNotes]: 'Notas',
    [StringTemplates.ContactAdd]: 'Adicionar contato',
    [StringTemplates.ContactDelete]: 'Excluir contato',
    [StringTemplates.ContactDeleteConfirm]: 'Tem certeza de que deseja excluir o contato "{{name}}"?',
    [StringTemplates.ContactEdit]: 'Editar contato',
    [StringTemplates.OutboundContactHeader]: 'Contato da Chamada',
    [StringTemplates.OutboundContactLabel]: 'Selecionar um contato',
    [StringTemplates.ContactSearch]: 'Pesquisar contatos',
    [StringTemplates.NoItems]: 'Nenhum item encontrado',
    [StringTemplates.CurrentPage]: 'Página {{current}} de {{total}}',
    [StringTemplates.NextPage]: 'Próxima página',
    [StringTemplates.PreviousPage]: 'Página anterior',
    [StringTemplates.AllowColdTransfer]: 'Permitir transferências frias para este contato',
    [StringTemplates.AllowWarmTransfer]: 'Permitir transferências quentes para este contato',
  },
  'es-MX': esMX,
  'es-ES': esES,
});
